import assert from 'node:assert/strict';
import { chromium, expect } from '@playwright/test';
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
try {
  const page = await browser.newPage({ viewport: { width: 1366, height: 768 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://localhost:3000/es');
  const robot = page.locator('.hero-robot');
  await expect(robot).toHaveAttribute('data-ready', 'true', { timeout: 90000 });
  await expect(robot.locator('canvas')).toBeVisible();
  await page.getByRole('button', { name: 'Pausar galería de fondo' }).click();
  await page.waitForTimeout(1500);
  await page.screenshot({ path: 'artifacts/robot-desktop.png' });
  await expect(page.locator('.robot-toggle')).toHaveCount(0);
  await expect(robot).toHaveAttribute('data-playback', 'running');
  await page.evaluate(() => window.scrollTo({ top: document.getElementById('about').offsetTop, behavior: 'instant' }));
  await expect(robot).toHaveAttribute('data-playback', 'paused');
  await page.waitForTimeout(1500);
  await page.screenshot({ path: 'artifacts/robot-about.png' });
  await page.getByRole('button', { name: 'Volver al inicio' }).click();
  await expect.poll(() => page.evaluate(() => scrollY)).toBe(0);
  await expect(robot).toHaveAttribute('data-playback', 'running');
  await page.setViewportSize({ width: 390, height: 600 });
  await expect(robot).toHaveCount(0);
  await page.waitForTimeout(1500);
  await page.screenshot({ path: 'artifacts/robot-mobile.png' });
  await page.setViewportSize({ width: 1366, height: 768 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.reload();
  await expect(robot).toHaveAttribute('data-ready', 'true', { timeout: 90000 });
  await expect(robot).toHaveAttribute('data-playback', 'paused');
  await expect(robot.locator('canvas')).toBeVisible();
  await page.screenshot({ path: 'artifacts/robot-reduced.png' });
  assert.deepEqual(errors, []);
  let requests = 0;
  await page.route('https://prod.spline.design/**/scene.splinecode', route => { requests++; return route.abort(); });
  await page.goto('http://localhost:3000/en');
  await expect(page.getByText('The robot could not load')).toBeVisible({ timeout: 30000 });
  const before = requests;
  await page.getByRole('button', { name: 'Retry', exact: true }).click();
  await expect.poll(() => requests).toBeGreaterThan(before);
  await expect(page.getByRole('link', { name: 'Download CV' })).toBeInViewport({ ratio: 1 });
  console.log('Spline: desktop scene without pause button, automatic playback, no mobile robot, reduced motion and error/retry verified.');
} finally { await browser.close(); }
