import { chromium } from "@playwright/test";

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1366, height: 768 } });
page.on("pageerror", (error) => console.error(error.message));
await page.goto("http://localhost:3000/es");
await page.evaluate(() => document.fonts.ready);
await page.waitForFunction(() => [...document.querySelectorAll("[data-hero-reveal]")].every((element) => element.getAttribute("style")?.includes("opacity: 1;")));
await page.screenshot({ path: "artifacts/hero-desktop.png" });
await page.evaluate(() => window.scrollTo({ top: window.innerHeight * 0.5, behavior: "instant" }));
await page.waitForTimeout(700);
await page.screenshot({ path: "artifacts/chapter-transition.png" });
await page.evaluate(() => window.scrollTo({ top: document.getElementById("about").offsetTop, behavior: "instant" }));
await page.waitForFunction(() => [...document.querySelectorAll("[data-about-reveal]")].every((element) => getComputedStyle(element).opacity === "1"));
await page.screenshot({ path: "artifacts/about-desktop.png" });
console.log(await page.title());
await page.setViewportSize({ width: 390, height: 600 });
await page.goto("http://localhost:3000/es");
await page.waitForFunction(() => [...document.querySelectorAll("[data-hero-reveal]")].every((element) => element.getAttribute("style")?.includes("opacity: 1;")));
await page.screenshot({ path: "artifacts/hero-mobile.png" });
await page.getByRole("button", { name: "Abrir menú" }).click();
await page.waitForFunction(() => getComputedStyle(document.querySelector(".mobile-menu-panel")).opacity === "1");
await page.screenshot({ path: "artifacts/menu-mobile.png" });
await page.getByRole("button", { name: "Cerrar menú" }).click();
await page.evaluate(() => window.scrollTo({ top: document.getElementById("about").offsetTop, behavior: "instant" }));
await page.waitForFunction(() => [...document.querySelectorAll("[data-about-reveal]")].every((element) => getComputedStyle(element).opacity === "1"));
await page.locator("#about").screenshot({ path: "artifacts/about-mobile.png" });
await browser.close();
